### ISSUE TITLE
Receive Group List 

### ISSUE THREAD

**Issue by Ubsurb** [sm0rux/at-d878uv#19]
Jättebra jobb med kodpluggen! Enkel och välorganiserad.

En fråga.
Det ligger ligger en receive group list på alla digitala kanaler, Default, denna innehåller alla talgrupper som finns i kodpluggen. Är tanken med den att man skall slippa behöva använda Digital monitor-funktionen i 878an? För med den vald på alla digitala kanaler så hör man alla talgrupper (som ligger i receive group list) oavsett om digital monitor är på eller av.

Ett förslag.
Man kanske skall kan byta ut talgruppen Regional SM0 (2400) mot regionstalgruppen där repeatrarna ligger. 
T.ex. kanal Alingsas 3 får Regional SM6 (2406) som talgrupp eftersom den ligger i distrikt 6, och 2406 ligger som statisk talgrupp på repeatern.

Mvh. Peter
SM6WKB

**Comment by sm0rux** [comment]
> Jättebra jobb med kodpluggen! Enkel och välorganiserad.

Tack!

Om du känner till knasigheter på https://sk6ba.se/repeater/karta/ så gör gärna korrigeringar där så kommer de med i nästa release av kodpluggen :)

> En fråga.
> Det ligger ligger en receive group list på alla digitala kanaler, Default, denna innehåller alla talgrupper som finns i kodpluggen. Är tanken med den att man skall slippa behöva använda Digital monitor-funktionen i 878an? För med den vald på alla digitala kanaler så hör man alla talgrupper (som ligger i receive group list) oavsett om digital monitor är på eller av.

Jag har tagit med de talgrupper jag vill lyssna på. Ibland slår jag på Digi Moni men det är sällsynt. Å andra sidan kör jag mest via egen hotspot så jag bekränsar redan i hotspoten vilka talgrupper jag vill lyssna på.

> Ett förslag.
> Man kanske skall kan byta ut talgruppen Regional SM0 (2400) mot regionstalgruppen där repeatrarna ligger.
> T.ex. kanal Alingsas 3 får Regional SM6 (2406) som talgrupp eftersom den ligger i distrikt 6, och 2406 ligger som statisk talgrupp på repeatern.

Mycket bra förslag, kommer i nästa release!

> Mvh. Peter
> SM6WKB
