### ISSUE TITLE
Hallandsåsen

### ISSUE THREAD

**Issue by sm0rux** [sm0rux/at-d878uv#2]
Sedan har jag ett tillägg. Repeatern på Hallandsåsen, SK7RQX har nu även DMR. 145.7875 / 145.1875 MHz, CC:7. Bör kanske finnas med i roaming zone för både SM6 och SM7 eftersom den är nåbar från båda distrikten.

Rapporterat av SM0RGM Stefan

**Comment by sm0rux** [comment]
Fört in Hallandsas i Channels, Roaming Channel och Roaming Zone (SM7)

**Comment by sm0rgm** [comment]
Jag har kört sträckan Göteborg -> Helsingborg och söderut i Halland är det lite ont om DMR-repeatrar men Hallandsåsen går att nå redan någonstans mellan Falkenberg och Halmstad så ett förslag är att göra ett undantag och placera repeatern Hallandsås både i SM7 Skane och SM6 Ovriga samt båda roamingzonerna SM6 och SM7.

**Comment by sm0rux** [comment]
Jag håller med om att vi gör ett undantag för Hallansåsen. Dock finns det ytterligare ett alternativ:

Ha med repeatern i roaming-zonerna för SM6 och SM7 men bara ha den med i SM7 Skåne-zonen. Den kan ju nämligen bara vara med i en scan-lista och kanske finns det en fördel om scan-listorna överensstämmer med de vanliga zonerna (inte med roaming-zonerna).

Eller?
