### ISSUE TITLE
Bryggad talgrupp

### ISSUE THREAD

**Issue by sm5gxq** [sm0rux/at-d878uv#20]
Hej!

Eftersom du har med de andra bryggade talgrupperna, så kan jag tipsa om 240721. 

Den är bryggad till analog FM på SK7RFL Algutsrum samt SK7RN Böda|Borgholm|Mörbylånga.

Det går även en bulle på söndagar kl 09:00.

Jag har även kollat uppgifterna om SK7RFL och SK7RN i dina filer och det ser korrekt ut!

Peter
SM5GXQ

**Comment by sm0rux** [comment]
Hej Peter,

Tack för bekräftelsen på att info om SK7RFL och SK7RN är rätt :)

Vad gäller talgrupper så har jag med de svenska talgrupperna i https://brandmeister.network/?page=talkgroups. Försök få SM0TSC Johan att lägga till 240721 så tar jag med den i kodpluggen.

73 de SM0RUX Pontus

**Comment by sm0rux** [comment]
Aha - nu ser jag att 240216 inte är en talgrupp i https://brandmeister.network/?page=talkgroups - jag lägger till 240721 strax :)
