### ISSUE TITLE
Kanal 32 Nynashamn 1 har fel Subton

### ISSUE THREAD

**Issue by johanthid** [sm0rux/at-d878uv#23]
32 | Nynashamn 1 | 145.71250 | 145.11250 | A-Analog | Mid | 12.5K | Off | 77.0

Rätt ska vara 123.00
Källa:
http://www.sk0bj.se/nra/?p=333

**Comment by sm0rux** [comment]
Tack, jag gissar att du har skickat uppdatering till SK6BA? :)

**Comment by sm0rux** [comment]
Ahh, nu ser jag - det är jag som lagt in fel subton, det är ju redan 123.0 på SK6BA :)
