### ISSUE TITLE
Död repeater

### ISSUE THREAD

**Issue by SA7TOR** [sm0rux/at-d878uv#6]
295	Ystad	434.92500	432.92500 Har varit död de senaste 4 åren.

de SA7TOR

**Comment by sm0rux** [comment]
Fixar detta under dagen. Anmäler du till sk6ba.se så att repeatern försvinner från deras sajt också?

**Comment by sm0rux** [comment]
Är nu fixat. Filer märkta "2020-11-06 Fix" är korrigerade. Släpper däremot ingen ny release idag då det kanske kommer fler korrigeringar!

Låter issuet vara öppet tills du svarar på om du meddelar SK6BA.

73's de SM0RUX Pontus

**Comment by sm0rux** [comment]
Hade tid över och har anmält till SK6BA att repeatern i Ystad är QRT

**Comment by SA7TOR** [comment]
Jag meddelar SK6BA.

Hämta Outlook for Android<https://aka.ms/ghei36> för det har SA7TOR gjort.

________________________________
