### ISSUE TITLE
DMR-repeater i Malmö

### ISSUE THREAD

**Issue by sm0rux** [sm0rux/at-d878uv#8]
Har fått reda på av SA7SSE att det finns en DMR-repeater i Malmö. Har meddelat SK6BA och snart kommer den in i kodpluggen

**Comment by sm0rux** [comment]
Fixat!

**Comment by sm0rgm** [comment]
Malmö, 434.775/432.775 ligger som simplex i kodpluggen.

**Comment by sm0rux** [comment]
Det är redan åtgärdat, men inte i en ny release.

Däremot ser jag nu att ett antal repeatrar ligger utan Default Receive-list. Jag fixar detta nu och släpper en ny release om en stund.
