### ISSUE TITLE
SG7DMR QRT

### ISSUE THREAD

**Issue by SA7TOR** [sm0rux/at-d878uv#9]
DMR SG7DMR City: Blentarp / Romeleåsen
Output: 434.6125 TXshift: -2.000
Status: QRT

**Comment by sm0rux** [comment]
Tack snälla för beskedet!

**Comment by SA7TOR** [comment]
Jag har meddelat SK6BA :)

**Comment by sm0rux** [comment]
Tillsammans kan vi göra kodpluggen och SK6BA bättre :) Stort tack!

**Comment by sm0rux** [comment]
Fixat

**Comment by SA7TOR** [comment]
Har nu gått igenom DMR repeatrar i Skåne. De röda är QRT i dag 2020-11-07.

De SA7TOR


Från: Pontus Falk <notifications@github.com>
Skickat: den 6 november 2020 11:32
Till: sm0rux/at-d878uv <at-d878uv@noreply.github.com>
Kopia: Tord Hallenberg <sa7tor@ssa.se>; Author <author@noreply.github.com>
Ämne: Re: [sm0rux/at-d878uv] SG7DMR QRT (#9)


Tillsammans kan vi göra kodpluggen och SK6BA bättre :) Stort tack!
